file_format: "1"
id: totem
name: TOTEM
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: [seeed_xiao]
features:
  - keys
  - studio
siblings:
  - totem_dongle
  - totem_left
  - totem_right